name: Daily Stock Report

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install -r requirements.txt

      - name: Debug secrets
        env:
         SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          echo "SUPABASE_URL is: $SUPABASE_URL"

      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python auto_mail.py
